## MongoDB Exploratory Data Analysis (EDA)
    Purpose: This notebook performs Exploratory Data Analysis (EDA) on data stored in MongoDB.

In [2]:
import sys
import os
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

from pprint import pprint

# Add project root to Python path
sys.path.append(os.path.abspath(".."))

from utils.connection import get_mongo_db

In [3]:
db = get_mongo_db()

print("Connected to MongoDB")
print("Database:", db.name)

Connected to MongoDB
Database: museum_db

In [6]:
collections = db.list_collection_names()
print(collections)

['museum', 'museum_hours', 'subject', 'canvas_size', 'work', 'product_size', 'artist']

In [7]:
collection_stats = []

for collection_name in collections:
    count = db[collection_name].count_documents({})
    
    collection_stats.append({
        "collection": collection_name,
        "documents": count
    })

collection_stats = pd.DataFrame(collection_stats)

collection_stats

     collection  documents
0        museum         57
1  museum_hours        351
2       subject       6771
3   canvas_size        200
4          work      14776
5  product_size     110347
6        artist        421

In [ ]:
collection = db["product_size"]
data = list(collection.find({}))
df = pd.DataFrame(data)
df.head()

,_id,work_id,size_id,sale_price,regular_price,updated_at
0,6a27cafbe86a9e33856ab9c4,160228,24,85,85,2026-06-09T22:33:05
1,6a27cafbe86a9e33856ab9c5,160236,24,85,85,2026-06-09T22:33:05
2,6a27cafbe86a9e33856ab9c6,160236,30,95,95,2026-06-09T22:33:05
3,6a27cafbe86a9e33856ab9c7,160244,24,85,85,2026-06-09T22:33:05
4,6a27cafbe86a9e33856ab9c8,160244,30,95,95,2026-06-09T22:33:05

In [17]:
df.shape
df.columns.tolist()
df.dtypes
df.info()
df.describe(include="all").T

<class 'pandas.DataFrame'>
RangeIndex: 110347 entries, 0 to 110346
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   _id            110347 non-null  object
 1   work_id        110347 non-null  int64
 2   size_id        110347 non-null  object
 3   sale_price     110347 non-null  int64
 4   regular_price  110347 non-null  int64
 5   updated_at     110347 non-null  str
dtypes: int64(3), object(2), str(1)
memory usage: 7.1+ MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
_id,110347,110347,6a27cafbe86a9e33856ab9c4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
work_id,110347.0,NaN,NaN,NaN,78651.654227,73617.239155,178.0,18210.0,28435.0,147731.0,209770.0
size_id,110347.0,164.0,3040.0,4609.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sale_price,110347.0,NaN,NaN,NaN,413.775653,192.176274,10.0,285.0,365.0,535.0,1115.0
regular_price,110347.0,NaN,NaN,NaN,746.012352,383.403091,75.0,485.0,655.0,975.0,2235.0
updated_at,110347,1,2026-06-09T22:33:05,110347,NaN,NaN,NaN,NaN,NaN,NaN,NaN